<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.byzatic</groupId>
        <artifactId>Industrial-Pipeline-TesseraModules</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>service-prometheus-export</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>service-prometheus-export</name>

    <properties>
        <fully.qualified.main.class>${project.groupId}.tessera.industrial_pipeline.services.service_prometheus_export.PrometheusExportService</fully.qualified.main.class>
    </properties>

    <dependencies>

        <dependency>
            <groupId>io.github.byzatic</groupId>
            <artifactId>lib-tessera-dfe-project-io</artifactId>
            <version>${version.tessera_project_io}</version>
        </dependency>

        <dependency>
            <groupId>io.github.byzatic</groupId>
            <artifactId>sharedresources-project-common</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
            <version>2.3.2</version>
        </dependency>

        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-core</artifactId>
            <version>1.3.8</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-exporter-httpserver</artifactId>
            <version>1.3.8</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-instrumentation-jvm</artifactId>
            <version>1.3.8</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>

</project>
